Add end to end test harness for operator upgrade
openshift/rbac-permissions-operator pull request #148
Opened 2023-10-04 21:16 UTC by YiqinZhang

### What type of PR is this?
test

### What this PR does / why we need it?
Add end-to-end test harness for operator upgrade.
Passed the test suite locally.

### Which Jira/Github issue(s) this PR fixes?

Card 1102: https://issues.redhat.com/browse/SDCICD-1102

### Special notes for your reviewer:

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR

2023-10-05 23:07 UTC, weherdh commented
@YiqinZhang Some jobs failed, could you please check?

2023-10-06 06:49 UTC, a7vicky requested changes

2023-10-06 06:49 UTC, a7vicky commented on build/Dockerfile
> +FROM
```suggestion
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.8-1037
```

2023-10-06 06:49 UTC, a7vicky commented on build/Dockerfile.olm-registry
> +FROM
```suggestion
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.8-1037
```

2023-10-06 15:44 UTC, closed without merging